name: redurx
version: 1.0.0
description: A thin layer of a Redux-based state manager on top of RxDart.

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  rxdart: ^0.27.0

dev_dependencies:
  test: ^1.5.1+1
